# Author: Rick Candell
# Org: NIST
# License: Public Domain
# Configuration file format
# Put a - between each entry 
# Specify the following:
#   name: name of action (optional)
#   type: plan_exec_arm, move_arm, move_gripper, sleep, 'noop'
#   spec:  for all move types, specify the name of the goal as joint positions
#             for all plan types, specify the eef position as [x, y, z, r, p, y]
#             for sleep, specify seconds as a float
#   wait_depend: full name of dependency
#   set_depend: name of dependency to update once action is complete

-
    type: reset
    spec: 0
-
    type: move_arm
    spec: cand   
    set_depend: /arm_1/ready_to_begin 
-
    type: move_gripper
    spec: opening 
-
    type: noop
    wait_depend: /arm_2/ready_to_begin
-
    type: move_arm
    spec: premach1
-
    type: move_arm
    spec: mach1 
-    
    type: move_gripper
    spec: closing
-
    # The robot needs time to manipulate the gripper
    type: sleep
    spec: 1.8
-
    type: move_arm
    spec: premach1
- 
    type: move_arm
    spec: cand
-
    type: move_arm
    spec: cand
-
    type: move_arm
    spec: trans1
    set_depend: /arm_1/ready_with_ball    
-
    wait_depend: /arm_2/got_ball
    type: move_gripper
    spec: opening
-
    # The robot needs time to manipulate the gripper
    type: sleep
    spec: 1.8
-
    type: move_arm
    spec: post_trans1    
-
    set_depend: /arm_1/ball_released
    type: move_arm
    spec: cand
-
    type: move_arm
    spec: ready_tight_spot
-
    # sleep time to allow PID to settle
    type: sleep
    spec: 2.0       
-
    type: move_arm
    spec: tight_spot
-
    type: move_gripper
    spec: closing
-
    # The robot needs time to manipulate the gripper
    type: sleep
    spec: 2.0
    set_depend: /arm_1/ball_released
-
    type: move_arm
    spec: ready_tight_spot
-
    type: move_arm
    spec: premach1
-
    type: move_arm
    spec: mach1
-
    type: move_gripper
    spec: opening
-
    # The robot needs time to manipulate the gripper
    type: sleep
    spec: 3.0
    set_depend: /arm_1/ball_released
-
    type: move_arm
    spec: cand
-
    type: move_arm
    spec: prepick_rob1
-
    wait_depend: /arm_2/ball_on_ramp
    # This is just to wait for the ball to roll. Can be longer if necessary.
    # Note: this will eventually be a proximity sensor
    type: sleep
    spec: 5.0 
-
    type: move_arm
    spec: pick_rob1
-
    type: move_gripper
    spec: closing
-
    type: sleep
    spec: 1.0
-
    type: move_arm
    spec: prepick_rob1    
-
    type: move_arm
    spec: ready_tight_spot
-
    type: sleep
    spec: 2.0    
-
   type: move_arm
   spec: tight_spot
-
    type: move_gripper
    spec: opening
-
    type: sleep
    spec: 2.0    
-
    type: move_arm
    spec: ready_tight_spot
-
    type: move_arm
    spec: cand

